### ISSUE TITLE
pd.read_csv() doesn't take generator as input

### ISSUE THREAD

**Issue by prajjwal1** [radekosmulski/quickdraw#1]
I was having optimization issues to get images, so i referred to your nb. Your function takes in a generator which you get from `.iterdir()`. I referred to pandas docs as well, `pd.read_csv()` doesn't take in generator. I was getting the same error. How were you able to do ? I'm on pandas 0.23.
I tried iterating through folder, reading it one by one and then concatenating it but it crashes my instance.

**Comment by radekosmulski** [comment]
I am not sure I understand. Are you getting an error when you run the code?

I iterate over the csvs in a directory and read each one separately.

**Comment by prajjwal1** [comment]
I don't get any error but i think there's an issue with `save_ims_from_df`. When you do `df=pd.read_csv(path)`, you're passing the generator to pandas since you're doing `.iterdir()`. Now the folder gets created but it's empty, when i tried debugging, i found that pandas doesn't allow you to pass generator objects into `read_csv`. So you will have to iterate over it and then concatenate each one of them. That's what i think should be the solution.

**Comment by radekosmulski** [comment]
Thanks for the observation but I don't pass a generator to `pd.read_csv`. I do map over the paths to the csv files, but that is slightly different.
