### ISSUE TITLE
minor typos

### ISSUE THREAD

**Issue by mprostock** [radekosmulski/quickdraw#2]
Hi, thanks for doing this, very interesting.
Just to make something good even better a few minor things:

**readme.md:**

`train_simplified.csv `should be train_simplified **.zip**

the unzip command should end with `-d train `(which is the new dir created a line above) and not in `-d trains_csvs`

data_prep notebook:
I had to manuall add `import PIL` to my imports. You use that in the `save_ims_from_df` func.
This used to be included in from` fastai.imports import *` but maybe isn't anymore in v1?!

**Comment by radekosmulski** [comment]
Hi Marc - thank you for the information, appreciate it. I think this should now be fixed. Let me know please if anything else would be off.
